---
- hosts: all
  become: true
  vars_files: 
    - vars/default.yml

  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{ docker_compose_dir }}/{{ item }}"
        state: directory
        mode: '0755'
      loop: "{{ container_name }}"
    - name: Copy compose source templates
      template:
        src: "docker-compose/{{ item }}/docker-compose.yml"
        dest: "{{ docker_compose_dir }}/{{ item }}/docker-compose.yml"
        mode: 0600
      loop: "{{ container_name }}"
    - name: Create and start services
      community.docker.docker_compose:
        project_src: "{{ docker_compose_dir }}/{{ item }}"
      loop: "{{ container_name }}"