---
version: "2.1"
services:
  portainer_agent:
    image: portainer/agent:2.11.0
    ports:
      - "9001:9001" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - /var/lib/docker/volumes:/var/lib/docker/volumes 
  portainer_server:
    image: portainer/portainer-ce:2.11.0
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../appData_config/portainer:/data