---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - ../appData_config/jellyfin/library:/config
      - ../appData_config/jellyfin/tvseries:/data/tvshows
      - ../appData_config/jellyfin/movies:/data/movies
    ports:
      - 8096:8096