---
version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    ports:
    - "80:80"
    - "443:443"
    volumes:
      - ../appData_config/heimdall:/config
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/Toronto
      